version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "YOURALIAS/js-e2e-express-react-mongodb-server"
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "YOURALIAS/js-e2e-express-react-mongodb-client"
    ports:
      - "3000:3000"
    depends_on:
      - server
    links:
      - server