version: '3'

# docker-compose -f ./docker-compose.azure.yml up --build --remove-orphans --force-recreate --no-cache

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.azure
    image: "CONTAINERREGISTRYdiberry3.azurecr.io/server:v19Fullstack"
    ports:
      - "3005:3005"
    environment:
      - ENVIRONMENT=production
      - DATABASE_NAME=my-local-docker-compose-database
      - DATABASE_COLLECTION_NAME=
      - REACT_APP_API_BASE_URL=
      - DATABASE_URL=mongodb://diberry-cosmosdb-mongodb:AIzw5WiA0HUw1qgBuZS0lpUoKMtcdxqWpB6knn9klnxiWpBvzMZ00zHEVhSz1sRdKYPQOPM8SZxurJkTR8I8Ag==@diberry-cosmosdb-mongodb.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@diberry-cosmosdb-mongodb@
    restart: always